### ISSUE TITLE
Is there any documentation to help me out with this?

### ISSUE THREAD

**Issue by patrickbolle** [vazco/meteor-universe-autoform-scheduler#4]
Thanks!

**Comment by luixal** [comment]
+1

**Comment by goncalovelosa** [comment]
+1

**Comment by radekmie** [comment]
This package is currently unsupported (in some way), but I'll try to make up some documentation. If something is wrong, please let me know. If everything will be all right, then I'll copy it to the README.

### Description

This field uses (and stores in db) as a [RRule](https://github.com/aramk/rrule/). Basically, if you want to start using it, go with `RRule.fromString(string)` (where `string` is the output from this field) and then use it as described [here](https://github.com/aramk/rrule/#occurrence-retrieval-methods).

### Usage

In your schema:

``` js
new SimpleSchema({
    // ...
    schedule: {
        type: String,
        autoform: {
            type: 'universe-scheduler'
        }
    }
    // ...
});
```

Or directly in your template:

``` html
{{!-- ... --}}
{{> afQuickField name="schedule" type="universe-scheduler"}}
{{!-- ... --}}
```

**Comment by luixal** [comment]
I guess this is configured to be used only with 'aldeed:autoform@4.0.0'. Autoform is currently in version 5.8.1.

Anyway, could you post an screenshot? Just to see if it matches what I have in mind so I can work on a fork.

Thanks!

**Comment by radekmie** [comment]
Few screenshots (not all available options).

### 1

![screenshot from 2016-07-14 14-02-41](https://cloud.githubusercontent.com/assets/1379064/16838835/cd4e7f6c-49cb-11e6-85e1-616992b4f542.png)

### 2

![screenshot from 2016-07-14 14-03-00](https://cloud.githubusercontent.com/assets/1379064/16838836/cd4f1e68-49cb-11e6-8b12-b64298b87d38.png)

### 3

![screenshot from 2016-07-14 14-03-15](https://cloud.githubusercontent.com/assets/1379064/16838837/cd53b8a6-49cb-11e6-8503-eb34675ed1b6.png)

**Comment by luixal** [comment]
Hmm... looks great!

I'll think about forking it and adding support for LaterJs (we're using it instead of rrule).

Thanks!

**Comment by radekmie** [comment]
Nice to hear that.
Looking forward your fork!

**Comment by krishaamer** [comment]
Thanks! In general more examples and documentation of the whole Universe would be awesome!

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
